[tool.poetry]
name = "djangoproject"
version = "0.1.0"
description = ""
authors = ["Toomas <toomas.taro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
